---


- name: copy template sudoers
  template:
    src: /var/ansible/roles/sudoers/templates/{{ sudoers }}
    dest: /etc/sudoers.d/
    owner: root
    group: root
    backup: yes
    mode: 0440
    validate: '/usr/sbin/visudo -cf %s'

...

