---

- hosts: localhost
  gather_facts: no

  tasks:
  - name: Creation de la machine virtuelle
    vmware_guest:
      hostname: "{{ vcenter_hostname }}"
      username: "{{ vcenter_username }}"
      password: "{{ vcenter_password }}"
      validate_certs: no
      folder:
      name: "{{ namevm }}"
      state: poweredon
      guest_id: centos
      esxi_hosname: "{{ esxi_hostname }}"
      
      disk:
      - size_gb: 40
        type: eagerzeroedthick
        datastore: "{{ datastore }}"

      hardware:
        memory_mb: 1024
        num_cpus: 1
        scsi: paravirtual

      networks:
      - name: VM Network
        mac:
        ip: 192.168.1.33
        netmask: 255.255.255.0
        device_type: vmxnet3
      wait_for_ip_address: yes
    
    delegate_to: localhost
    register: deploy_vm
