---

- hosts: all
  vars:
    fstype_1_value: 'xfs'
    fstype_2_value: 'ext4'

  tasks:
  - name: create group by os
    group_by:
      key: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}"
  
  
  - set_fact:
     fstype_value: "{{ fstype_1_value if (ansible_distribution_major_version == '7') else fstype_2_value }}"

  remote_user: speypelat
  become: yes
  become_method: sudo
  roles:
   # - role: fs_add_multiple
   - { role: fs_rm_multiple, fs_list: "{{ rm_fs }}" }

...

