---
# Aide pour executer le playbook
# ansible-playbook update_server.yml --extra-vars "packages=nomdupackage" --limit server 
# exemple: ansible-playbook update_server.yml --extra-vars "packages=nmap-ncat.x86_64" --limit

- hosts: all
  remote_user: speypelat
  become: yes
  become_method: sudo

  vars:
      my_packages: "{{ packages }}"

  tasks:    
  - name: Mise à jour du serveur
    yum:
      name: '*'
      state: latest


  - name: installation de packages supplementaires
    yum:
      name: "{{ my_packages }}"
      state: present
    ignore_errors: yes

...
