- hosts: all
  tasks:
  - name: create group by os
    group_by:
      key: "{{ ansible_distribution }}_{{ ansible_distribution_major_version }}"


  remote_user: speypelat
  become: yes
  become_method: sudo
  roles:
  - { role: newuser, newusers: "{{ local_users }}" }
